services:
  eth-dutch-monitor:
    build: .
    container_name: eth-dutch-monitor
    volumes: [".:/app", "/app/.venv"]
    working_dir: /app
    command: >
      bash -c "
      uv venv --clear &&
      . .venv/bin/activate &&
      uv sync &&
      export $(grep -v '^#' .env | xargs) &&
      silverback run --network :mainnet
      "
    restart: unless-stopped